CREATE DATABASE compostApp;

USE compostApp;
CREATE TABLE USERS(
    ts_creation TIMESTAMP NOT NULL DEFAULT NOW()::TIMESTAMP,
    row_id SERIAL NOT NULL,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    password TEXT NOT NULL,
    CONSTRAINT USERS_PK
        PRIMARY KEY (row_id),
    CONSTRAINT EMAIL_NO_REPEAT UNIQUE(email)
);

CREATE TABLE QUESTIONS(
    ts_creation TIMESTAMP NOT NULL DEFAULT NOW()::TIMESTAMP,
    row_id SERIAL NOT NULL,
    user_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    CONSTRAINT QUESTIONS_PK
        PRIMARY KEY (row_id),
    CONSTRAINT QUESTIONS_FK_USERS
        FOREIGN KEY (user_id)
        REFERENCES USERS(row_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE ANSWERS(
    ts_creation TIMESTAMP NOT NULL DEFAULT NOW()::TIMESTAMP,
    row_id SERIAL NOT NULL,
    user_id INTEGER NOT NULL,
    question_id INTEGER NOT NULL,
    content TEXT NOT NULL,
    CONSTRAINT ANSWERS_PK
        PRIMARY KEY (row_id),
    CONSTRAINT ANSWERS_FK_USERS
        FOREIGN KEY (user_id)
        REFERENCES USERS(row_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT ANSWERS_FK_QUESTIONS
        FOREIGN KEY (question_id)
        REFERENCES QUESTIONS(row_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE LIKES(
    ts_creation TIMESTAMP NOT NULL DEFAULT NOW()::TIMESTAMP,
    row_id SERIAL NOT NULL,
    user_id INTEGER NOT NULL,
    answer_id INTEGER NOT NULL,
    answer_like BOOLEAN NOT NULL DEFAULT FALSE,
    answer_dislike BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT LIKES_PK
        PRIMARY KEY (row_id),
    CONSTRAINT LIKES_FK_USERS
        FOREIGN KEY (user_id)
        REFERENCES USERS(row_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT LIKES_FK_ANSWERS
        FOREIGN KEY (answer_id)
        REFERENCES ANSWERS(row_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE LIKES2(
    ts_creation TIMESTAMP NOT NULL DEFAULT NOW()::TIMESTAMP,
    row_id SERIAL NOT NULL,
    user_id INTEGER NOT NULL,
    answer_id INTEGER NOT NULL,
    reaction INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT LIKES2_PK
        PRIMARY KEY (row_id),
    CONSTRAINT LIKES2_FK_USERS
        FOREIGN KEY (user_id)
        REFERENCES USERS(row_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT LIKES2_FK_ANSWERS
        FOREIGN KEY (answer_id)
        REFERENCES ANSWERS(row_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
